export const GET_PLAYER_RANKING = "GET_PLAYER_RANKING";
export const GET_TEAM_RANKING = "GET_TEAM_RANKING";

export const GET_VENUES = "GET_VENUES";
export const GET_VENUE_BYCOUNTRY = "GET_VENUE_BYCOUNTRY";

export const GET_TEAM = "GET_TEAM";
export const GET_TOURNAMENT = "GET_TOURNAMENT";

export const GET_HEADLINES = "GET_HEADLINES";
export const GET_SINGLE_HEADLINE = "GET_SINGLE_HEADLINE";
export const GET_FIXTURES = "GET_FIXTURES";
export const SEARCH_PLAYER = "SEARCH_PLAYER";
export const GET_MATCHESBYTYPE = "GET_MATCHESBYTYPE";
export const GET_RECENT_MATCHES = "GET_RECENT_MATCHES";

export const LOGIN = "LOGIN";
export const ADD_PLAYERS = "ADD_PLAYERS";
export const ADD_PLAYERS_TYPE = "ADD_PLAYERS_TYPE";
export const GET_PLAYERS = "GET_PLAYERS";
export const ADD_ADMIN = "ADD_ADMIN";
export const GET_USERS = "GET_USERS";

// Type for Matches
export const GET_MATCH_DETAILS = "GET_MATCH_DETAILS";
export const GET_SCORECARD = "GET_SCORECARD";
export const MATCH_SUMMARY = "MATCH_SUMMARY";
export const SEARCH_TEAM = "SEARCH_TEAM";

//Type for player -Rohan
export const ALL_PLAYERS = "ALL_PLAYERS";
export const PLAYER_SEARCH = "PLAYER_SEARCH";
// Type for admin -Yash
export const SEND_OTP = "SEND_OTP";
export const ADD_NEW_TEAM = "ADD_NEW_TEAM";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const ERROR_TYPE = "ERROR_TYPE";

// Global Search
export const GET_SEARCH = "GET_SEARCH";

//Type for team -RohanK
export const SEARCH_TEAM_FOR_VIEW_TEAM_PAGE = "SEARCH_TEAM_FOR_VIEW_TEAM_PAGE";
export const GET_TEAM_BY_ID = "GET_TEAM_BY_ID";
export const GET_MATCHES_BY_TEAM = "GET_MATCHES_BY_TEAM";
export const GET_MATCHES_BY_TEAM_AND_TYPE = "GET_MATCHES_BY_TEAM_AND_TYPE";
export const GET_TEAM_STATS = "GET_TEAM_STATS";
export const GET_PLAYER_STATS_FOR_TEAMS = "GET_PLAYER_STATS_FOR_TEAMS";
export const GET_PLAYER_STATS_FOR_TEAMS_BOWLER =
  "GET_PLAYER_STATS_FOR_TEAMS_BOWLER";
export const GET_MATCHES_BY_DATE = "GET_MATCHES_BY_DATE";

// Type for Graphs
export const TEAM_STATS_GRAPH_ODI = "TEAM_STATS_GRAPH_ODI";
export const TEAM_STATS_GRAPH_TEST = "TEAM_STATS_GRAPH_TEST";
export const TEAM_STATS_GRAPH_T20 = "TEAM_STATS_GRAPH_T20";
export const MANHATTAN_GRAPH_MATCH = "MANHATTAN_GRAPH_MATCH";
export const PIECHART_BATSMAN_INNINGS1 = "PIECHART_BATSMAN";
export const PIECHART_BOWLER_INNINGS1 = "PIECHART_BOWLER";
export const PIECHART_BATSMAN_INNINGS2 = "PIECHART_BATSMAN";
export const PIECHART_BOWLER_INNINGS2 = "PIECHART_BOWLER";
