export const GET_PLAYER_RANKING = "GET_PLAYER_RANKING";
export const GET_TEAM_RANKING = "GET_TEAM_RANKING";

export const GET_VENUES = "GET_VENUES";
export const GET_VENUE_BYCOUNTRY = "GET_VENUE_BYCOUNTRY";

export const GET_TEAM = "GET_TEAM";
export const GET_TOURNAMENT = "GET_TOURNAMENT";

export const GET_HEADLINES = "GET_HEADLINES";
export const GET_SINGLE_HEADLINE = "GET_SINGLE_HEADLINE";
export const GET_FIXTURES = "GET_FIXTURES";
export const SEARCH_PLAYER = "SEARCH_PLAYER";
export const GET_RECENT_MATCHES = "GET_RECENT_MATCHES";
