export const GET_PLAYER_RANKING = "GET_PLAYER_RANKING";
export const GET_TEAM_RANKING = "GET_TEAM_RANKING";

export const GET_VENUES = "GET_VENUES";
export const GET_VENUE_BYCOUNTRY = "GET_VENUE_BYCOUNTRY";

export const GET_TEAM = "GET_TEAM";
export const GET_TOURNAMENT = "GET_TOURNAMENT";

export const GET_HEADLINES = "GET_HEADLINES";
export const GET_SINGLE_HEADLINE = "GET_SINGLE_HEADLINE";
export const GET_FIXTURES = "GET_FIXTURES";
export const SEARCH_PLAYER = "SEARCH_PLAYER";
export const GET_MATCHESBYTYPE = "GET_MATCHESBYTYPE";
export const GET_RECENT_MATCHES = "GET_RECENT_MATCHES";

export const LOGIN = "LOGIN";
export const ADD_PLAYERS = "ADD_PLAYERS";
export const ADD_PLAYERS_TYPE = "ADD_PLAYERS_TYPE";

export const GET_USERS = "GET_USERS";
export const SEARCH_TEAM_FOR_VIEW_TEAM_PAGE = "SEARCH_TEAM_FOR_VIEW_TEAM_PAGE";
export const GET_TEAM_BY_ID = "GET_TEAM_BY_ID";
export const GET_MATCHES_BY_TEAM = "GET_MATCHES_BY_TEAM";
export const GET_TEAM_STATS = "GET_TEAM_STATS";
export const GET_PLAYER_STATS_FOR_TEAMS = "GET_PLAYER_STATS_FOR_TEAMS";
export const GET_PLAYER_STATS_FOR_TEAMS_BOWLER =
  "GET_PLAYER_STATS_FOR_TEAMS_BOWLER";
